name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTg3Y2Y1YTEtNDEwNi00YWMxLTljNDAtN2Q4NTg3ODlmOGRmIiwidGVuYW50X2lkIjoiNWI4ZjMxMDZlZWRlMWY2Y2I3NDU4OWYwNWMwODY1MDNkY2JjOWZmZmViNjdkMjU5MmM3NmUwOGFjMmY2YWY2ZSIsImludGVybmFsX3NlY3JldCI6ImI5NTRlMTNiLWMyZTMtNGVlNi04NzA4LWFiYWM1NzM5MDBkNiJ9.vC45RiNL5cZqB30qOPJ1_2k6qlnMmQSQbP-C22U7yXU"
JWT_SECRET="MYSECRETPASSSWORD"
